DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    expired boolean DEFAULT true,
    locked boolean DEFAULT true,
    failed_login_attempts bigint DEFAULT 0,
    credentials_expire_on timestamp without time zone,
    enabled boolean DEFAULT false,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    user_id character varying(255)
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments (
    id bigint NOT NULL,
    comment character varying(255),
    created_on timestamp without time zone,
    created_by_user bigint,
    created_on_issue_id bigint
);

ALTER TABLE comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS user_confirmation_tokens CASCADE;

CREATE TABLE user_confirmation_tokens (
    id bigint NOT NULL,
    confirmed_at timestamp without time zone,
    created_at timestamp without time zone,
    expires_at timestamp without time zone,
    token character varying(255),
    user_id bigint NOT NULL
);

ALTER TABLE user_confirmation_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_confirmation_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS project_confirmation_tokens CASCADE;

CREATE TABLE project_confirmation_tokens (
    id bigint NOT NULL,
    confirmed_at timestamp without time zone,
    created_at timestamp without time zone,
    expires_at timestamp without time zone,
    token character varying(255),
    project_id bigint NOT NULL
);

ALTER TABLE project_confirmation_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME project_confirmation_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS issue_access_requests CASCADE;

CREATE TABLE issue_access_requests (
    id bigint NOT NULL,
    changed_state_on timestamp without time zone,
    request_id character varying(255),
    requested_on timestamp without time zone,
    approval_user bigint,
    requested_by_user bigint,
    resource bigint,
    issue bigint
);

ALTER TABLE issue_access_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME issue_access_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS issues CASCADE;

CREATE TABLE issues (
    id bigint NOT NULL,
    assigned_on timestamp without time zone,
    closed_on timestamp without time zone,
    created_on timestamp without time zone,
    description character varying(255),
    environment character varying(255),
    issue_id character varying(255),
    modified_on timestamp without time zone,
    priority character varying(255),
    reproducing_steps character varying(255),
    status character varying(255),
    title character varying(255),
    version character varying(255),
    assigned_user bigint,
    closed_by_user bigint,
    created_by_user bigint,
    modified_by_user bigint,
    project_id bigint,
    tester bigint
);

ALTER TABLE issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS project_access_requests CASCADE;

CREATE TABLE project_access_requests (
    id bigint NOT NULL,
    changed_state_on timestamp without time zone,
    request_id character varying(255),
    requested_on timestamp without time zone,
    approval_user bigint,
    requested_by_user bigint,
    resource bigint,
    project bigint
);

ALTER TABLE project_access_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME project_access_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DROP TABLE IF EXISTS projects CASCADE;

CREATE TABLE projects (
    id bigint NOT NULL,
    start_date timestamp without time zone,
    target_end_date timestamp without time zone,
    actual_end_date timestamp without time zone,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    project_key character varying(255) NOT NULL
);

ALTER TABLE projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


ALTER TABLE ONLY user_confirmation_tokens
    ADD CONSTRAINT user_confirmation_tokens_pkey PRIMARY KEY (id);

    ALTER TABLE ONLY project_confirmation_tokens
    ADD CONSTRAINT project_confirmation_tokens_pkey PRIMARY KEY (id);


ALTER TABLE ONLY issue_access_requests
    ADD CONSTRAINT issue_access_requests_pkey PRIMARY KEY (id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT issues_pkey PRIMARY KEY (id);


ALTER TABLE ONLY project_access_requests
    ADD CONSTRAINT project_access_requests_pkey PRIMARY KEY (id);


ALTER TABLE ONLY projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


ALTER TABLE ONLY projects
    ADD CONSTRAINT project_name_uk UNIQUE (name);


ALTER TABLE ONLY users
    ADD CONSTRAINT user_email_uk UNIQUE (email);


ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT closed_by_user_id_fk FOREIGN KEY (closed_by_user) REFERENCES users(id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id);


ALTER TABLE ONLY comments
    ADD CONSTRAINT created_on_issue_id_fk FOREIGN KEY (created_on_issue_id) REFERENCES issues(id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT tester_id_fk FOREIGN KEY (tester) REFERENCES users(id);


ALTER TABLE ONLY comments
    ADD CONSTRAINT created_by_user_id_fk FOREIGN KEY (created_by_user) REFERENCES users(id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT created_by_user_id_fk FOREIGN KEY (created_by_user) REFERENCES users(id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT modified_by_user_id_fk FOREIGN KEY (modified_by_user) REFERENCES users(id);


ALTER TABLE ONLY user_confirmation_tokens
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY project_confirmation_tokens
    ADD CONSTRAINT project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id);


ALTER TABLE ONLY issues
    ADD CONSTRAINT assigned_user_id_fk FOREIGN KEY (assigned_user) REFERENCES users(id);