spring:
  config:
    activate:
      on-profile:
        - test
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/bugtracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_CREDS_USR}
    password: ${MAIL_CREDS_PSW}
    properties:
      mail:
        smtp:
          auth: auth
          starttls:
            enable: true
