application:
  frontend:
    url: https://alexbosca.github.io/BugTracker
  backend:
    baseUrl: https://bugtracker-xtnz.onrender.com

logging:
  level:
    org:
      springframework:
        security: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: validate
