application:
  name: Bug Tracker System

server:
  port: 8082
  servlet:
    context-path: /api/v1/bug-tracker
  tomcat:
    relaxed-path-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'
    relaxed-query-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'

spring:
  profiles:
    active: dev
