spring:
  config:
    activate:
      on-profile:
        - dev
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/import-data/import-projects.sql, classpath:/sql/import-data/import-teams.sql, classpath:/sql/import-data/import-users.sql, classpath:/sql/import-data/import-confirmation-tokens.sql, classpath:/sql/import-data/import-teams-on-project.sql, classpath:/sql/import-data/import-issues.sql, classpath:/sql/import-data/import-users-in-teams.sql
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/bugtracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_CREDS_USR}
    password: ${MAIL_CREDS_PSW}
    properties:
      mail:
        smtp:
          auth: auth
          starttls:
            enable: true

email:
  confirmation-link: http://localhost:4200/confirm-account?token=%s
