server:
  port: 8081
  servlet:
    context-path: /api/v1/bug-tracker
  tomcat:
    relaxed-path-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'
    relaxed-query-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'

logging:
  file:
    path: logs/
    name: logs/application.log

application:
  name: Bug Tracker System
