server:
  port: 8081
  servlet:
    context-path: /api/v1/bug-tracker
  tomcat:
    relaxed-path-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'
    relaxed-query-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'

application:
  name: Bug Tracker System

spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema/schema.sql
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/bugtracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always