server:
  port: 8081
  servlet:
    context-path: /api/v1/bug-tracker
  tomcat:
    relaxed-path-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'
    relaxed-query-chars:
      - '['
      - '\'
      - ']'
      - '^'
      - '`'
      - '{'
      - '|'
      - '}'

application:
  name: Bug Tracker System

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/bugtracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: public
    locations: classpath:db/migrations
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_CREDS_USR}
    password: ${MAIL_CREDS_PSW}
    properties:
      mail:
        smtp:
          auth: auth
          starttls:
            enable: true