name: Backend CI/CD

on:
  repository_dispatch:
    types: [trigger-backend]
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    # * To be enabled when ITs are implemented
    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: ${{ secret.POSTGRES_USER }}
    #       POSTGRES_PASSWORD: ${{ secret.POSTGRES_PASSWORD }}
    #       POSTGRES_DATABASE: ${{ secret.POSTGRES_DATABASE }}
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd "pg_isready -U postgres" 
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -f backend clean install -DskipTests

      - name: Run Unit Tests
        run: mvn -f backend test

      # * To be enabled when ITs are implemented
      # - name: Run Integration Tests
      #   run: mvn -f backend failsafe:integration-test failsafe:verify

      - name: SonarCloud Scan
        run: mvn -f backend sonar:sonar -Dsonar.projectKey=ro.alexportfolio:backend -Dsonar.token=${{ secrets.SONAR_TOKEN }}
