name: Backend CI Pipeline

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - 'feature/**'
      - 'master'
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - 'master'

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    # * To be enabled when ITs are implemented
    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: ${{ secret.POSTGRES_USER }}
    #       POSTGRES_PASSWORD: ${{ secret.POSTGRES_PASSWORD }}
    #       POSTGRES_DATABASE: ${{ secret.POSTGRES_DATABASE }}
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd "pg_isready -U postgres" 
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix shallow clone warning
        run: |
          git fetch --unshallow || true
          git fetch --tags || true

      - name: Set up Java 17
        uses: ./.github/actions/checkout-and-setup
        with:
          tool-name: 'java'
          tool-version: '17'
          distribution: 'oracle'
          working-directory: './backend'

      - name: Build and Test
        working-directory: ./backend
        env:
          KEY_STORE_PASS: ${{ secrets.KEY_STORE_PASS }}
          MAIL_CREDS_USR: ${{ secrets.MAIL_CREDS_USR }}
          MAIL_CREDS_PSW: ${{ secrets.MAIL_CREDS_PSW }}
        run: mvn clean test package verify

      - name: Publish Backend Unit Test Report
        uses: turing85/publish-report@v2
        with:
          comment-header: 🧪 Backend Unit Test Report
          comment-message-success: |
            <details>
              <summary><h3>🎉 {0} passed</h3></summary>

              <h4>🧪 Unit Tests Results </h4>

              | Passed | Failed | Skipped |
              |--------|--------|---------|
              | ✅ {1} | ❌ {2} | ⚠️ {3}   |

              You can see the report [here]({4}).
            </details>
          comment-message-failure: |
            <details>
              <summary><h3>⛈️ {0} failed</h3></summary>

              <h4>🧪 Unit Tests Results </h4>

              | Passed | Failed | Skipped |
              |--------|--------|---------|
              | ✅ {1} | ❌ {2} | ⚠️ {3}   |

              You can see the report [here]({4}).
            </details>
          report-fail-on-error: true
          report-name: Backend Unit Tests
          report-path: 'backend/target/surefire-reports/TEST*.xml'

      - name: Run Checkstyle
        working-directory: ./backend
        run: mvn checkstyle:checkstyle

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT: ${{ secrets.SONAR_PROJECT_BACKEND }}

        run: |
          SONAR_ARGS="
            -Dsonar.organization=$SONAR_ORG
            -Dsonar.projectKey=$SONAR_PROJECT
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=$SONAR_TOKEN
            -Dsonar.sources=src/main/java,src/main/resources
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.exclusions=**/*Test*.java,**/test/**
            -Dsonar.exclusions=**/target/**,**/static/**,**/db/migration/**,**/*.sql,**/application*.yml,**/application*.properties
            -Dsonar.scm.revision=$GITHUB_SHA
          "

          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "Running PR analysis"

            SONAR_ARGS="$SONAR_ARGS
              -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
              -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF
              -Dsonar.pullrequest.base=${{ github.base_ref }}
            "
          else
            echo "Running branch analysis"

            SONAR_ARGS="$SONAR_ARGS
              -Dsonar.branch.name=$GITHUB_REF_NAME
            "
          fi

          mvn sonar:sonar $SONAR_ARGS

      # * To be enabled when ITs are implemented
      # - name: Run Integration Tests
      #   run: mvn -f backend failsafe:integration-test failsafe:verify

      - name: SonarCloud Quality Gate
        uses: ./.github/actions/check-quality-gate
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: ro.alexportfolio:backend
          pull_request: ${{ github.event.pull_request.number }}
          branch_name: ${{ github.ref_name }}
