name: Frontend CI/CD

on:
  repository_dispatch:
    types: [trigger-frontend]
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      # - name: Lint code
      #   run: npm run lint
      #   working-directory: frontend

      - name: Run Unit Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: frontend

      - name: Set up JDK 17 for Sonar Scan
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: SonarCloud Scan
        run: npx sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=bugtracker_frontend -Dsonar.organization=bugtracker -Dsonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info -Dsonar.token=${{ secrets.SONAR_TOKEN }}
