name: Fronend CI Pipeline

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - 'feature/**'
      - 'master'
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - 'master'

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix shallow clone warning
        run: |
          git fetch --unshallow || true
          git fetch --tags || true

      - name: Setup Node
        uses: ./.github/actions/checkout-and-setup
        with:
          tool-name: 'node'
          tool-version: '22.12.0'
          working-directory: './frontend'

      - name: Inject API URL
        working-directory: ./frontend
        run: |
          sed -i "s|__API_URL__|${{ secrets.API_URL }}|g" src/environments/environment.ts

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build -- --base-href /BugTracker/

      - name: Fix index file for GitHub Pages
        working-directory: ./frontend
        run: |
          cp dist/frontend/browser/index.csr.html dist/frontend/browser/index.html

      - name: ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Test + Coverage
        working-directory: ./frontend
        run: npm run test:coverage

      - name: Publish Frontend Unit Tests Report
        uses: turing85/publish-report@v2
        with:
          comment-header: 🧪 Frontend Unit Test Report
          comment-message-success: |
            <details>
              <summary><h3>🎉 {0} passed</h3></summary>

              <h4>🧪 Unit Tests Results </h4>

              | Passed | Failed | Skipped |
              |--------|--------|---------|
              | ✅ {1} | ❌ {2} | ⚠️ {3}   |

              You can see the report [here]({4}).
            </details>
          comment-message-failure: |
            <details>
              <summary><h3>⛈️ {0} failed</h3></summary>

              <h4>🧪 Unit Tests Results </h4>

              | Passed | Failed | Skipped |
              |--------|--------|---------|
              | ✅ {1} | ❌ {2} | ⚠️ {3}   |

              You can see the report [here]({4}).
            </details>
          report-fail-on-error: true
          report-name: Frontend Unit Tests
          report-path: 'frontend/test-results/unit-test-results.xml'

      - name: SonarCloud Scan
        working-directory: ./frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT: ${{ secrets.SONAR_PROJECT_FRONTEND }}

        run: |
          SONAR_ARGS="
            -Dsonar.organization=$SONAR_ORG
            -Dsonar.projectKey=$SONAR_PROJECT
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=$
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info  \
            -Dsonar.sourceEncoding=UTF-8  \
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/environments/**,**/*.module.ts,**/main.ts,**/polyfills.ts,**/test.ts,**/setup-jest.ts,**/index.ts,**/app-routing.module.ts,**/assets/**,**/*.config.ts,**/jest.config.ts,**/karma.conf.js,**/tailwind.config.js,**/vite.config.ts,**/*.mock.ts  \
            -Dsonar.coverage.exclusions=**/main.ts,**/polyfills.ts,**/environments/**,**/*.module.ts,**/app-routing.module.ts,**/test.ts,**/index.ts  \
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.scm.revision=$GITHUB_SHA
          "

          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "Running PR analysis"

            SONAR_ARGS="$SONAR_ARGS
              -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
              -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF
              -Dsonar.pullrequest.base=${{ github.base_ref }}
            "
          else
            echo "Running branch analysis"

            SONAR_ARGS="$SONAR_ARGS
              -Dsonar.branch.name=$GITHUB_REF_NAME
            "
          fi

          mvn sonar:sonar $SONAR_ARGS

      - name: SonarCloud Quality Gate
        uses: ./.github/actions/check-quality-gate
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: bugtracker_frontend
          pull_request: ${{ github.event.pull_request.number }}
          branch_name: ${{ github.ref_name }}
