name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven

    - name: Test with Maven
      run: mvn -f backend test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      with:
        args:
            -Dsonar.projectKey=ro.alexportfolio:backend
            -Dsonar.organization=alexbosca
            
        projectBaseDir: backend/
